{$DEFINE CADImportVCL}
{$DEFINE CADExportVCL}

//CADSoftTools_CADImportVCL+CADExportVCL.inc  is used as default .inc file CADImportVCL.inc 
//It is aimed for clients who use CAD Import VCL + CAD Export VCL package
// and for development in CADSoftTools.
// Also private demo package with compilable DCU / OBJ for CAD Import VCL and CAD Export VCL
// is provided with this version of CADSoftTools.inc

